packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  "@prisma/client": true
  "@prisma/engines": true
  prisma: true
  esbuild: true

# Evita que `pnpm run`/`exec` re-instale automáticamente en cada ejecución.
verifyDepsBeforeRun: false